version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.6.15
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    env_file:
      - variables.env
    volumes:
      - "./local_queue/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - delphi

  db:
    image: postgres
    env_file:
      - variables.env
    ports:
      - "5432:5432"
    networks:
      - delphi

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - delphi

  delphi_api:
    build:
      context: ./delphi_api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - variables.env
    volumes:
      - ./delphi_api:/usr/src/app
    ports:
      - "5000:5000"
    networks:
      - delphi
    depends_on:
      - db

  delphi_subscriber:
    build:
      context: ./delphi_api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - variables.env
    command: bash -c "PYTHONPATH=/usr/src/app && sleep 15 && python3 app/event_processor/main.py"
    volumes:
      - ./delphi_api:/usr/src/app
    depends_on:
      - rabbitmq
    networks:
      - delphi

  contract_subscriber:
    build:
      context: ./contract_subscriber
    restart: always
    env_file:
      - variables.env
    command: bash -c "npm install && npm run contract"
    volumes:
      - ./contract_subscriber:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - delphi
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
      - redis

  factory_subscriber:
    build:
      context: ./contract_subscriber
    restart: always
    env_file:
      - variables.env
    command: bash -c "npm install && npm run factory"
    volumes:
      - ./contract_subscriber:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - delphi
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
      - redis

  # mock_contract_subscriber:
  #   build:
  #     context: ./mock_contract_subscriber
  #   restart: always
  #   env_file:
  #     - variables.env
  #   #command: npm start
  #   volumes:
  #     - ./mock_contract_subscriber:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - rabbitmq
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - delphi

networks:
  delphi:
    name: delphi
