version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.6.15
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    env_file:
      - variables.env
    volumes:
      - "./local_queue/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - delphi

  db:
    image: postgres
    env_file:
      - variables.env
    ports:
      - "5432:5432"
    networks:
      - delphi

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - delphi

  delphi_api:
    build:
      context: ./delphi_api
      dockerfile: Dockerfile.web
    restart: always
    env_file:
      - variables.env
    ports:
      - "5000:5000"
    networks:
      - delphi
    depends_on:
      - db
      - redis

  event_processor:
    build:
      context: ./delphi_api
      dockerfile: Dockerfile.event-processor
    restart: always
    env_file:
      - variables.env
    command: bash -c "PYTHONPATH=/usr/src/app && sleep 15 && python3 app/event_processor/main.py"
    depends_on:
      - rabbitmq
    networks:
      - delphi

  contract_subscriber:
    build:
      context: ./contract_subscriber
      dockerfile: Dockerfile.contract-subscriber
    restart: always
    env_file:
      - variables.env
    networks:
      - delphi
    depends_on:
      - rabbitmq
      - redis

  factory_subscriber:
    build:
      context: ./contract_subscriber
      dockerfile: Dockerfile.factory-subscriber
    restart: always
    env_file:
      - variables.env
    networks:
      - delphi

networks:
  delphi:
    name: delphi
